# Generated by Django 2.2.12 on 2022-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('decription', models.CharField(max_length=200)),
                ('identifier', models.SlugField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
